### ISSUE TITLE
Refactor deployment of conjur-master to use one StatefulSet plus HAProxy

### ISSUE THREAD

**Issue by kgilpin** [conjurdemos/kubernetes#3]
The current system of having 3 Conjur appliance Pods and a Service that switches between them using labels is kind of working, but it's not ideal. Ideally, we should be letting Kubernetes route the traffic automatically, and we should be using features like liveness and readiness probes to determine when Pods are up, down, available, and/or need to be restarted. This can be accomplished using the following architecture:

1) A single conjur-master StatefulSet consisting of 3 Pods. (replaces the current system of 3 StatefulSets, each with one pod).
2) A headless Service which matches the 3 Pods. This is required to establish the Pod DNS names, which will be used in step (3).
3) An HAProxy ReplicaSet (or Deployment?) which serves as a health-checking load balancer to the conjur-master StatefulSet. The HAProxy should be configured to route all traffic to the healthy master, using the /health URL. HAProxy can be run redundantly (e.g. 2 Pods). The HAProxy can be configured with the known DNS names of each of the 3 Pods in the conjur-master StatefulSet, since have stable DNS names. 
4) A conjur-master Service which sits in front of the HAProxy ReplicaSet. liveness and readiness probes on the HAProxy Pods will be used to ensure that the Service routes traffic only to live+ready HAProxy containers.

With the architecture above, all clients can direct traffic to the DNS name of the conjur-master Service. There will not be any need for clients to manage the IP address of conjur-master using /etc/hosts or any such complication. Clients simply use the DNS name of the conjur-master service and Kubernetes takes care of the rest. This service can also be "published" (e.g. as a minikube NodePort), for access from outside the cluster. Again this is a stable name that does not need to be changed due to master failover. 

Followers should replicate the master through the conjur-master Service (and then through HAProxy to the active master).

The YAML for the headless service and StatefulSet should be similar to:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master-headless
spec:
  ports:
  - port: 443
  clusterIP: None
  selector:
    app: conjur-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-master
spec:
  serviceName: conjur-master
  replicas: 3
  template:
    metadata:
      labels:
        app: conjur-master
    spec:
      containers:
      - name: conjur-master
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
```
Note: See above the proper names for each port

Note: The HAProxy layer is necessary because Conjur standby nodes report "unhealthy" when they are in standby mode. For reasons I won't go into right here, that prevents us from using a Kubernetes Service directly in front of the conjur-master StatefulSet.
